### PR TITLE
fix: Whitelist cli args

### LINKED ISSUE #550: Use whitelist for CLI arguments instead of blacklist
The Fether application accepts command line configuration arguments. Certain arguments
are blacklisted. The use of a blacklist is not recommended, as
new features could be added to the underlying Parity node, resulting in unintended extra
functionality invokable by CLI.

We should allow `--chain`.
If any other argument is needed, users can still spin up the node separately and pass the arguments they wish.

### PR DESCRIPTION
**Pull request by amaurymartiny**
fix #550 

Only two flags possible:
- `--chain`
- `--no-run-parity`: kept this one, iirc was requested a couple of times in parity ui, and harmless

Any other flags will exit Fether with error code != 0.

### CODE REVIEW

File: packages/fether-electron/src/main/app/cli/index.js [hunk 1]
```diff
@@ -31,24 +32,6 @@ cli
...
-      // -psn_*: https://github.com/paritytech/fether/issues/188
-      // --ws-interface: we don't pass down this flag, because fether only allows 127.0.0.1 as WS interface
-      .filter(
-        arg =>
-          !arg.startsWith('--inspect') &&
-          !arg.startsWith('-psn_') &&
-          !arg.startsWith('--ws-interface')
-      )
-  );
+  .parse(process.argv);
```
Comment (axelchalon) [inline packages/fether-electron/src/main/app/cli/index.js]: My hunch is that Electron or MacOs would be pass down flags to Electron, which are unexpected on our side and would make the program exit with error code != 0 (because we don't allow unknown arguments anymore). I think I would keep the filtering of `process.argv` ?

```js
parse(
    process.argv
      // We want to ignore some flags and not pass them down to Parity:
      // --inspect: `electron-webpack dev` runs Electron with the `--inspect` flag for HMR
      // -psn_*: https://github.com/paritytech/fether/issues/188
      // --ws-interface: we don't pass down this flag, because fether only allows 127.0.0.1 as WS interface
      .filter(
        arg =>
          !arg.startsWith('--inspect') &&
          !arg.startsWith('-psn_') &&
          !arg.startsWith('--ws-interface')
      )
```

Comment (amaurymartiny) [reply packages/fether-electron/src/main/app/cli/index.js]: It seems that `--inspect` is not passed by `electron-webpack` anymore, so we can remove that one. `--ws-interface` has been removed.

You're probably right, i'll keep `arg => !arg.startsWith('-psn_')` just to be sure
